# Generated by Django 4.2 on 2024-12-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstreapp', '0002_alter_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
