# Generated by Django 4.2 on 2024-12-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstreapp', '0005_remove_books_author_author_book_books_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='name',
            new_name='name_authr',
        ),
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
