# Generated by Django 4.2 on 2024-12-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstreapp', '0006_rename_name_books_name_authr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
